name: Build Binary

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Binary
      run: |
        docker build -t plugin_builder .
        docker run --rm -v ${PWD}:/project plugin_builder make
    - uses: actions/upload-artifact@v3
      with:
        name: Nintendont autoboot forwarder
        path: "*.dol"
        if-no-files-found: error
